//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIBROS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBROS()
        {
            this.PRESTAMOS = new HashSet<PRESTAMOS>();
        }
    
        public int ID_LIBRO { get; set; }
        public int ID_AUTOR { get; set; }
        public string TITULO { get; set; }
        public string GENERO { get; set; }
        public int ANIO_PUBLICACION { get; set; }
        public int VOLUMEN { get; set; }
        public int CAPITULO { get; set; }
        public string EDITORIAL { get; set; }
    
        public virtual AUTORES AUTORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMOS> PRESTAMOS { get; set; }
    }
}
