//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMOS
    {
        public int ID_LIBRO { get; set; }
        public int ID_PRESTAMO { get; set; }
        public System.DateTime FECHA_PRESTAMO { get; set; }
        public System.DateTime FECHA_DEV { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public int TELEFONO { get; set; }
        public string CORREO { get; set; }
        public string DIRECCION { get; set; }
        public bool PRESTAMO_DEVUELTO { get; set; }
    
        public virtual LIBROS LIBROS { get; set; }
    }
}
